find_optimal_departure_time:
  name: Find Optimal Departure Time
  description: Find the optimal departure time for a specific route within a given time range
  fields:
    route_name:
      name: Route Name
      description: The name of the route to find the optimal departure time for
      required: true
      example: "work_route"
      selector:
        text:
    start_time:
      name: Start Time
      description: Start of the time range to search (ISO format)
      required: true
      example: "2023-07-18T08:00:00"
      selector:
        datetime:
    end_time:
      name: End Time
      description: End of the time range to search (ISO format)
      required: true
      example: "2023-07-18T10:00:00"
      selector:
        datetime:
    interval:
      name: Interval
      description: Time interval between checks in minutes
      required: false
      default: 30
      example: 15
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: minutes
